### ISSUE TITLE
SNP_call: ToDo

### ISSUE THREAD

**Issue by FabianGrammes** [FabianGrammes/cluster_pipelines#7]
Yo a little ToDo list for us: 

*General remarks*
1. In order not to drown in files, and to keep overview, I propose that we:
   - Delete the previous `.bam` files after each step
   - Add extensions to the `.bam` file for each processing step. For example after Split'N'Trim the `.bam` gets renamed from `file1.bam` to `file1.splitNtrim.bam`. After the next step that would be `file1.splitNtrim.nextstep.bam` etc.

- @FabianGrammes
- [x] Finish the whole `STAR` pipeline and test.
- [x] Finish the `picard` coding part. 

-  @timknut  
- [x] Finish and test the GATK part.
- [x] Integrate the GATK code into the `bash` script.

**Comment by timknut** [comment]
So @FabianGrammes , are you thinking to have the:
1. SNP_call.sh script be called from SNP_map.sh if proved as an argument to SNP_map.sh? OR: 
2. have it as an isolated pipeline? OR :
3. incorp the code in SNP_map.sh?

Think I'll be able to finish this next week some time.

**Comment by FabianGrammes** [comment]
@timknut I thought to do it the same way as `RNA_map.sh` which is: 
1. `SNP_call.sh` is a shell script that accepts input and contains the whole pipeline
2. Whenever someone calls `SNP_call.sh` the script is run and generates a folder tree for the output to be generated and the necessary `slurm` scripts (in the bash dir via `EOF`) with the individual parameters (like `.gtf`, genome `.fasta` etc)

**Comment by FabianGrammes** [comment]
Sounds good ?

**Comment by timknut** [comment]
Yes, but it might be convenient to incorporate the 2-pass method in rna_map.sh in genral, and then optionally run variant calling on the BAM from rna_map.sh with read groups and the SplitNCigarReads step. We can have a chat during :pizza:  maybe. :smile:

**Comment by FabianGrammes** [comment]
The names of the input files are generated from the `master_sheet` using awk. Here is the line:
`FILEBASE=$(awk ' NR=='$SLURM_ARRAY_TASK_ID+1' { print $2 ; }' master_test.txt)`.
`NR` is line number to be used and `print $2` specifies the 2nd column. So this generates the `$FILEBASE` variable to which you can append file endings 

So for your part you should start with the input: 
`BAM=star_2pass/$FILEBASE'-2pass-Aligned.out.sortedByCoord.dedupped.bam'

Test files are at:
`/mnt/users/fabig/RNAseq/test`

Good helg :)

**Comment by FabianGrammes** [comment]
Script works, tested on a small sample
